### ISSUE TITLE
add "hacktoberfest" tag

### ISSUE THREAD

**Issue by itsrahulhere** [atyant-yadav/Hactoberfest2020#214]
**Ineligible Repository**
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by atyant-yadav** [comment]
@itsrahulhere thanks for the concern, I've added hactoberfest as label.

happy coding :)

**Comment by itsrahulhere** [comment]
It is still showing *Ineligible Repository*.

*Ineligible Repository*
Your PR was submitted to a repository that is not participating in
Hacktoberfest. Maintainers of the repository can add the "*hacktoberfest*"
topic to their repository if they wish to participate. Alternatively, an
individual PR can be opted-in with a maintainer adding the
"hacktoberfest-accepted" label to the PR.

**Comment by atyant-yadav** [comment]
@itsrahulhere i've updated the "hactoberfest" tag and it might take some time to get accepted as a participating repo, and to reflect changes.

I hope it helps :)

**Comment by itsrahulhere** [comment]
*I got this mail pls read point number 3.*


October is here, and so is Hacktoberfest!

Before contributing to awesome open source projects this month, we have
some important updates to share with you.

After working closely with our friends at GitHub, we are happy to introduce
measures that are brand new to Hacktoberfest 2020.

   1. Pull requests can be made in any *participating* GitHub-hosted
   repositories/projects.

   2. Maintainers can opt-in to participate by classifying their projects
   with the hacktoberfest topic
   <https://pages.news.digitalocean.com/n/P000X2VE6I0EqL090aKDoc3>.

   3. Your pull requests will count toward your participation if they are
   in a repository with the hacktoberfest topic and once they have been
   merged, approved by a maintainer or labelled as hacktoberfest-accepted.

   4. Additionally, any pull request with the hacktoberfest-accepted label,
   submitted to any public GitHub repository, with or without the
   hacktoberfest topic, will be considered valid for Hacktoberfest.

All valid pull requests prior to Oct 3 (when these rules were introduced)
will be honored and counted toward completion of Hacktoberfest.

*Learn more
<https://pages.news.digitalocean.com/n/qoDE0V2a6L0XL903I0Er00c> about the
changes we've made that will affect your participation.*


Remember, there are tons of resources available to help get you started on
contributing quality pull requests:

   - Learn how to create your first pull request
   <https://pages.news.digitalocean.com/n/P000X2VE6I0EsL090aMDoc3>
   - Review this beginner’s checklist
   <https://pages.news.digitalocean.com/n/wIaDXLVE60000EoN20c3t09> for
   Hacktoberfest
   - Check out good first issues
   <https://pages.news.digitalocean.com/n/O090ELcD0320XE6u0O0VoaI> to
   contribute to
   - Chat with other contributors
   <https://pages.news.digitalocean.com/n/l9IcP0006oaE0D3VL0X0v2E> in
   Discord to learn tips on completing the challenge

We appreciate everyone doing their part to make Hacktoberfest a more
welcoming and positive experience for the global community. Please help
spread the word far and wide to get more repositories to opt in and partake
in the program.

If you have any questions, feedback or suggestions, feel free to reach out
to hacktoberfest@digitalocean.com
<https://pages.news.digitalocean.com/n/c0L03cEE06XI2oVDQ0aw900>.

Happy hacking,
Team DigitalOcean

**Comment by atyant-yadav** [comment]
4. Additionally, any pull request with the hacktoberfest-accepted label,
   submitted to any public GitHub repository, with or without the
   hacktoberfest topic, will be considered valid for Hacktoberfest.

@itsrahulhere 
see this if you are worried too much.

**Comment by PriyavKaneria** [comment]
The hactoberfest-accepted also requires the k in it.
Pls check
Thanks
