### ISSUE TITLE
Rename repo and label to "Hacktoberfest"

### ISSUE THREAD

**Issue by Melancholic** [atyant-yadav/Hactoberfest2020#242]
Current repo's name isn't correct, rename it to Ha**ck**toberfest2020 and update lebel to "ha**ck**toberfest"

**Comment by atyant-yadav** [comment]
@Melancholic its not necessary to rename repo to "hacktoberfest"

I have already added "hactoberfest" tag to this repo and "hectoberfest-accepted" tag to all PR's.

I hope it helps. :)
