### ISSUE TITLE
Correct code for Codechef All String

### ISSUE THREAD

**Issue by atyant-yadav** [atyant-yadav/Hactoberfest2020#7]
Make correct code for branch Codechef.

**Comment by Neha-Prabhu** [comment]
Hello, I'm new to Open source contribution. Can you please guide me as to what do to in a more elaborative way? :)

**Comment by atyant-yadav** [comment]
Welcome aboard!
The best way is to search for projects which interests you, go through Readme.md most of the instructions you will find there (like how to setup, about the project, where to contribute etc) and start with issues marked with beginner or easy tag.

More elaborated :- https://rubygarage.org/blog/how-contribute-to-open-source-projects

Feel free to ping me for any queries. Happy Hacking.

**Comment by pronayguha13** [comment]
hey @atyant  what is this new issue?

**Comment by atyant-yadav** [comment]
> hey @atyant what is this new issue?

It's regarding the correct code for Codechef problem "All String" .

Happy Coding!

**Comment by atyant** [comment]
Please correct the email id.
